spring.application.name: config
spring.profiles.default: dev

server.port: 8888

spring.cloud.config.server.git.uri: file:/home/jnb/workspace/codepot/config

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/