spring.application.name: films
spring.profiles.default: dev

server.port: 8069

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/