spring.application.name: rentals
spring.profiles.default: dev

server.port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/