spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show_sql: true
      format_sql: true

renting.price:
  PREMIUM: 40
  BASIC: 30